version: 2.1

orbs:
  slack: circleci/slack@4.4.4
  
jobs:
  deploy:
    docker:
      - image: cimg/base:2020.01
    steps: 
      - checkout
      - slack/notify:
          channel: slacktest
          event: always
          template: basic_success_1 
           
workflows:
  deploy_and_notify:
    jobs:
      - deploy:
          context: slack-secrets
 
