version: 2.1

orbs:
  slack: circleci/slack@4.1
  
jobs:
  deploy:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          command: npm run deploy
      - slack/notify:
          channel: slacktest
          event: always
          template: basic_success_1
          
workflows:
  deploy_and_notify:
    jobs:
      - deploy:
          context: slack-secrets
