version: 2.1
orbs:
  slack: circleci/slack@4.4.4
workflows:
  my-workflow:
    jobs:
      - build:
          context: 
            - slack-secrets
jobs:
  build:
    docker:
      - image: cimg/base:2021.11
    steps:
      - checkout 
      - run:
          command: |
            echo 'export TEMPLATE_JSON=$(cat ./templates/template.json)' >> $BASH_ENV
          name: |
            Store the content of the success.json template into a custom
            environment variable
      - slack/notify:
          template: TEMPLATE_JSON
          event: pass
          channel: slacktest
